steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gonitely-home-finder-api:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.workers', '-t', 'gcr.io/$PROJECT_ID/gonitely-home-finder-workers:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gonitely-home-finder-api']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gonitely-home-finder-workers']
  timeout: 180s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - "--namespace=staging"
  - set
  - image
  - deployment
  - gonitely-home-finder
  - gonitely-home-finder-api=gcr.io/$PROJECT_ID/gonitely-home-finder-api:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gonitely-staging-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - "--namespace=staging"
  - set
  - image
  - deployment
  - gonitely-home-finder-property-worker
  - gonitely-home-finder-property-worker=gcr.io/$PROJECT_ID/gonitely-home-finder-workers:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gonitely-staging-cluster'
