---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: production
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: devops@gonitely.com
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}
