---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: staging
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: devops@gonitely.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
